### ISSUE TITLE
 Cannot find module 'pinia/dist/pinia.mjs' 10:57:56

### ISSUE THREAD

**Issue by gllinzbk1** [liting-yes/nuxt-theme-liting#1]
ERROR  Cannot start nuxt:  Cannot find module 'pinia/dist/pinia.mjs' 10:57:56
Require stack:
- /data/user/lbadmin/develop/project/nuxt-theme-liting/index.js

**Comment by liting-yes** [comment]
Can you provide a repro repository? I haven't encountered this error when I was developing
